### ISSUE TITLE
odlozeny a zpozdeny dojezd

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#28]
obrazovka pro prijeti souteze se spozdenym dojezdnem je momentalne nevyhovujici. Dodavatel muze zadat za jak dlouho muze vyjet, to ale neni z pohledu zakaznika zajimave. melo by se zobrazovat kdy bude dodavatel u klienta. Prosim o nasledujici upravy:

- do uvodni stranky nabidky pridat radek Dojezd:  hodnota je ulozena v payloadu notifikace pole Order/ArrivalTime 

- do obrazovky s posunutim casu dojezdu nezobrazovat dny, hodiny, minuty, ale tento cas dojezdu jako dropdown s casy mozneho prijedu. Interval posunuti je po 5 minutach, privni hodnota je cas zaokrouhleny na 5 nahoru. Tedy pokud je dojezd 12:23 v dropdownu jsou hodnoty: 12:23, 12:25, 12:30 ... 13:25 

- do api request accept order se posle hodnota posunuti vypocitana z dropdownu.

-  do payloadu objednavky take pribude pole PostponedArrival (bool). Pokud je toto pole true jedna se o odlozeny dojezd a pod cas prijezdu je nutne pridat poznamku Odložený dojezd. Pokud se jedna o odlozeny dojezd neni mozne menit cas prijezdu.

 az budes pracovat na teto odbrazovce tak se take podivej na divne chovani zavreni te obrazovky se zadanim extra casu. Pokud ji zavru pozvanka se prijme s extra casem 0. Toto asi neni dobre, mel by ses vratit zpet na predchozi obrazovku a znova se rozhodovat zda pozvanku prijmout nebo odmitnout.

**Comment by veresvit** [comment]
NewTender screen - pridat pozadovany dojezt, zvyraznit modrou pokud neni dnesni.

nezobrazovat dialog s casem pri prijmuti

**Comment by veresvit** [comment]
AllowedDepartureDelayMinutes
