### ISSUE TITLE
Dotaz -  je mozne zmenit logo aplikace v notifikacnim panelu? 

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#37]
protoze se v notifikacnim panelu zobrazuje cernobile logo je nutne ho zmenit, je to mozne?

**Comment by veronikaforchova** [comment]
![logo_ea_black_transparent](https://user-images.githubusercontent.com/28568969/37952202-4dfd8a88-319f-11e8-83de-9d9ab79c96a0.png)

**Comment by veresvit** [comment]
Ahoj, jak jsem zminoval na skype, musi byt pouzta pouze bila barva na pruhlednem pozadi. :)

**Comment by veronikaforchova** [comment]
aha sorry to je dost divne, ale prebarvime.

**Comment by veronikaforchova** [comment]
![logo_ea_white_transparent](https://user-images.githubusercontent.com/28568969/38363566-6b821e7e-38d5-11e8-9037-4c48a99d52fd.png)
