### ISSUE TITLE
Zmeny v okne novy tender

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#40]
- zvyraznit pozadovane vozidlo v pozvance
- v ramci nabidky robrazovat claim sax code

**Comment by veresvit** [comment]
Jak zvyraznit? Tucne, podtrzeno, vetsi pismo, jina barva?

A v kterych mistech zobrazovat claim sax kod? Chcete k tomu pridat i nejakou ikonu?

**Comment by veronikaforchova** [comment]
a. tucne
b. misto duplikovaneho textu nova objednavka

**Comment by veronikaforchova** [comment]
proc se v okne nova objednavka zobrazuji ty prazdne radky? hlavne u udalosti a lokace klienta
