### ISSUE TITLE
Zmena ciselniku Reject Tender reason

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#41]
public enum RejectTenderReason
    {
        [Display(Name = "RejectTenderReason_Busy", ResourceType = typeof(EnumDescriptions))]
        Busy = 1,

        [Display(Name = "RejectTenderReason_Unequiped", ResourceType = typeof(EnumDescriptions))]
        Unequiped = 2,

        [Display(Name = "RejectTenderReason_TechnicalProblem", ResourceType = typeof(EnumDescriptions))]
        TechnicalProblem = 3,

        [Display(Name = "RejectTenderReason_LateArrival", ResourceType = typeof(EnumDescriptions))]
        LateArrival = 4,

        [Display(Name = "RejectTenderReason_AnotherCar", ResourceType = typeof(EnumDescriptions))]
        AnotherCar = 5
    }
}

**Comment by veresvit** [comment]
Jaky text by se mel zobrazit pro hodnotu 5?

**Comment by jakubjenis** [comment]
dej tam prosim: "Požadavek na jiné vozidlo"
