### ISSUE TITLE
Dotaz - je mozne zmenit zvuky aplikace na vlastni?

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#42]

**Comment by veresvit** [comment]
Mel by se pouzivat zvuk, ktery ma mobil jako vychozi vyzvaneni pro telefon. Pokud si zmeni vyzvanni, aplikace by se mela ozyvat jinym zvukem. 

Nad ramec tohoto by slo pridat nastaveni, kde by si uzivatel mohl vybrat vyzvaneni z dostupnych zvuku v telefonu.

**Comment by veronikaforchova** [comment]
oni by si chteli dodat nejake vlastni zvuky. Aby vsem zvonila aplikace stejne

**Comment by veresvit** [comment]
Ah, takto. Ano. Staci dodat mp3 soubor se zvukem.

**Comment by veronikaforchova** [comment]
prosim, pouzij zatime nejakou vlastni a pak ji prohodime, az ji dodaji. Taky tam dej jeste dalsi pro zvuk notifikace OrderAssigned pro roli ridic
