### ISSUE TITLE
Bug -  stisknutim tlacitka zpet po zobrazeni notifikace mi zmizne a zablokuje mi zobrazovani dalsich notifikaci

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#43]

**Comment by jakubjenis** [comment]
aplikace minimalizovana
kliknu na notifikaci NewTender
zobrazi se mi fullscreen nabidka souteze
kliknu zpet -> minimalizuju aplikaci
kliknu na otevreni aplikace
notifikace neni zobrazena

nejsem si na 100% jisty, jestli se podari replikovat pokazde, kazdopadne takhle mi to v EA ukazovali na jejich telefonech

**Comment by veresvit** [comment]
Aha, takze jde o zobrazeni screnu se stackem nabidek. Ano takto se to opravdu chova. Jedna se o to, ze tenhle nabidkovy screen je mimo standardni chovani hlavni casti aplikace. 

Pokud je potreba, budeme tam muset pridat nejakou dalsi logiku pri otevreni appky, aby se v pripade, ze je na stacku nejaka nabidka zobrazil screen s nabidkama.. tohle se ale zacne trosku bit v pripade, ze tam bude existovat neco jako ze ridic je na zakazce a v pripade ze otevre appku tak mu to vzdy zobrazi stack. bude to muset odklikat, etc. Mozna i nejake jine use cases budou problem, ktere ted nedomyslime.

Nebylo by efektnejsi, v pripade ze jsou nejake nabidky jeste nedoresene, uzivateli dat moznost si ty nabidky zobrazit rucne? Napriklad pridat nekde nejake tlacitko (app bar nahore?). Snad se vyhneme problemum s navigaci..

**Comment by veronikaforchova** [comment]
toto nevadi, pokud je ridic na zakazce, nebude zadne nabidky dostavat a pokud ano stejne je musi vyridit predne
