### ISSUE TITLE
prijeti objednavky z role ridic

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#48]
pokud ridic prijima soutez je neprijemne cekat par sekund na notifikaci OrderAssigned, proto by bylo dobre  pri odpovedi serveru 200 na accept order zavolat rest call orders/active a prehodit uzivatele do obrazovky na zasahu pokud je v odpovedi aktivni objednavka. Pokud je uzivatel jiz ve stavu na zasahu a prijde notifikace OrderAssigned applikace by jiz nemela zvonit.

**Comment by veresvit** [comment]
Takze pokud je to dispecer tak po prijeti muze dale prochazet nabidky.

Pokud je to ridic tak ho presmerujeme na obrazovku na zasah. Ostatni nabidky na stacku smazeme. Ok?

**Comment by veronikaforchova** [comment]
ano presne tak.
