### ISSUE TITLE
BUG -  velke zpomaleni aplikace

### ISSUE THREAD

**Issue by veronikaforchova** [conwarecz/eagps#49]
v posledni verzi doslo ke znacnemu zpomaleni aplikace. pro temer vsechny operace
-odhlaseni
-otevreni klavesnice opri prihlaseni
-otevreni okna s vyberem stavu vozidla
-prazdny seznam zakazek po prijeti objednavek (neni ulozeno v lokalni db?)

**Comment by veresvit** [comment]
Nepodarilo se mi zreprodukovat v aktualni verzi (starsi neprihlasim). Prosim o informace na jakych zarizenich a OS se to deje.
